<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-CNSGLOJC" failures="3" tests="3" name="Default test(failed)" time="0.097" errors="0" timestamp="2023-03-25T12:14:24 IST">
  <testcase classname="retryLogicDEmo.TestCaseExample" name="testCase01" time="0.029">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at retryLogicDEmo.TestCaseExample.testCase01(TestCaseExample.java:9)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testCase01 -->
  <testcase classname="retryLogicDEmo.TestCaseExample" name="testCase03" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at retryLogicDEmo.TestCaseExample.testCase03(TestCaseExample.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testCase03 -->
  <testcase classname="retryLogicDEmo.TestCaseExample" name="testCase02" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at retryLogicDEmo.TestCaseExample.testCase02(TestCaseExample.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testCase02 -->
</testsuite> <!-- Default test(failed) -->
